# Generated by Django 3.2.8 on 2021-10-24 15:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=2048)),
                ('author', models.CharField(max_length=2048, null=True)),
                ('book_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recsys.book')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('actions', models.ManyToManyField(related_name='actions', through='recsys.Action', to='recsys.Book')),
                ('recommendations', models.ManyToManyField(related_name='recommendations', through='recsys.Recommendation', to='recsys.Book')),
            ],
        ),
        migrations.AddField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recsys.user'),
        ),
        migrations.AddField(
            model_name='action',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recsys.book'),
        ),
        migrations.AddField(
            model_name='action',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recsys.user'),
        ),
    ]
