# Generated by Django 3.2.8 on 2021-10-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0004_action_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='actions',
            field=models.ManyToManyField(through='recsys.Action', to='recsys.Book'),
        ),
    ]
