# Generated by Django 3.2.8 on 2021-10-10 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0005_user_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
